apiVersion: v2
name: helm-warmupsh
description: A Helm chart for Kubernetes
namespace: warmupsh

type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: 11.1.20
    repository: https://charts.bitnami.com/bitnami
  - name: jenkins
    version: 5.7.12
    repository: https://charts.jenkins.io

mysql:
  auth:
    rootPassword: my-root-password
    database: my-database
    username: my-user
    password: my-password
  primary:
    persistence:
      enabled: true
      size: 8Gi