apiVersion: v2
name: helm-warmupsh
description: A Helm chart for Kubernetes
namespace: warmupsh

type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mysql
    version: 11.1.20
    repository: https://charts.bitnami.com/bitnami
  - name: jenkins
    version: 5.7.12
    repository: https://charts.jenkins.io
  - name: prometheus
    version: 25.29.0
    repository: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
  - name: grafana
    version: 8.5.11
    repository: https://grafana.github.io/helm-charts
    namespace: monitoring

repository:
  - name: istiod
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istiod
    version: 1.24.0-rc.0
    repository: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    createNamespace: true

mysql:
  auth:
    rootPassword: my-root-password
    database: my-database
    username: my-user
    password: my-password
  primary:
    persistence:
      enabled: true
      size: 8Gi

prometheus:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer